<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="1" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-07-25T17:03:23 IST" name="Default suite" finished-at="2022-07-25T17:05:13 IST" duration-ms="110492">
    <groups>
    </groups>
    <test started-at="2022-07-25T17:03:23 IST" name="Default test" finished-at="2022-07-25T17:05:13 IST" duration-ms="110492">
      <class name="testCases.LaptopTest">
        <test-method is-config="true" signature="initialization()[pri:0, instance:testCases.LaptopTest@7671cb68]" started-at="2022-07-25T17:03:23 IST" name="initialization" finished-at="2022-07-25T17:03:38 IST" duration-ms="14875" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initialization -->
        <test-method signature="Laptoptest()[pri:0, instance:testCases.LaptopTest@7671cb68]" started-at="2022-07-25T17:03:38 IST" name="Laptoptest" finished-at="2022-07-25T17:04:28 IST" duration-ms="50442" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Laptoptest -->
        <test-method is-config="true" signature="close()[pri:0, instance:testCases.LaptopTest@7671cb68]" started-at="2022-07-25T17:04:28 IST" name="close" finished-at="2022-07-25T17:04:29 IST" duration-ms="938" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- close -->
        <test-method is-config="true" signature="initialization()[pri:0, instance:testCases.LaptopTest@7671cb68]" started-at="2022-07-25T17:04:29 IST" name="initialization" finished-at="2022-07-25T17:04:46 IST" duration-ms="16836" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initialization -->
        <test-method signature="laptoptoCart()[pri:0, instance:testCases.LaptopTest@7671cb68]" started-at="2022-07-25T17:04:46 IST" name="laptoptoCart" finished-at="2022-07-25T17:05:13 IST" depends-on-methods="testCases.LaptopTest.Laptoptest" duration-ms="26626" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [0] but found [6]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [0] but found [6]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:907)
at org.testng.Assert.assertEquals(Assert.java:917)
at testCases.LaptopTest.laptoptoCart(LaptopTest.java:67)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- laptoptoCart -->
        <test-method is-config="true" signature="close()[pri:0, instance:testCases.LaptopTest@7671cb68]" started-at="2022-07-25T17:05:13 IST" name="close" finished-at="2022-07-25T17:05:13 IST" duration-ms="466" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- close -->
      </class> <!-- testCases.LaptopTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
